### ISSUE TITLE
Information Gathering & Content Discovery running on non existent subdomain

### ISSUE THREAD

**Issue by gopinath6** [SolomonSklash/chomp-scan#11]
Information Gathering & Content Discovery running on non existent subdomain  .
After subdomain enumeration create a single file with  valid subdomain . Use that list and perform next steps.
I think currently there is no single file having  reachable subdomains.

**Comment by SolomonSklash** [comment]
You'e right. I think the massdns results are being added to the all discovered domains list instead of a  separate resolvable domains list. I'll take a look.

**Comment by SolomonSklash** [comment]
I've fixed this issue. There is now a `all_resolved_domains.txt` file with all domains that massdns was able to resolve. This is now used for content discovery and information gathering. You'll still occasionally have some false positives, like domains that resolve but only have SSH open. Let me know how it works for you, and thanks for the feedback.

**Comment by gopinath6** [comment]
Thanks. Will test and share  the feedback
