### ISSUE TITLE
Subdomain takeover checker

### ISSUE THREAD

**Issue by gopinath6** [SolomonSklash/chomp-scan#13]
Can you add Subdomain takeover checker or other similar tool?
https://github.com/LukaSikic/subzy

**Comment by SolomonSklash** [comment]
[Subjack](https://github.com/haccer/subjack) is already included, does that work or does subzy do something different/better?

**Comment by gopinath6** [comment]
Ok. That should be fine.
Do you think 
https://github.com/hannob/snallygaster
https://github.com/tomnomnom/waybackurls
 can be added. Will it make tool heavy?

**Comment by SolomonSklash** [comment]
I've been meaning to add snallygaster, but inception looks like it does the same and more. I'll see how fast it is, being written in Go I expect it to be quick. If it is, I'll add it.

I'll look into waybackurls also.

Thanks for the feedback!

**Comment by SolomonSklash** [comment]
Actually, I'll ad snallygaster and inception. They have some overlap, but still both check different things.

**Comment by SolomonSklash** [comment]
Inception has been added. Snallygaster is too technically, but it's been quite slow so far. I'll play with it a bit more, but it may just be too slow to include.

**Comment by gopinath6** [comment]
Ok thanks.
Will check it out
