### ISSUE TITLE
Selecting particular tools of Information Gathering/Content discovery 

### ISSUE THREAD

**Issue by gopinath6** [SolomonSklash/chomp-scan#17]
By using command line,can you provide any options to select particular set of  tool under Information Gathering/Content discovery instead of  using all tools?

**Comment by SolomonSklash** [comment]
I'm rather torn on this issue. In theory I could make it so each tool can be selected individually, but doing that from the CLI would be pretty cumbersome, or would have to be done using interactive mode, which is not ideal.

I think the best solution is to use a configuration file. I'm looking into what it will take to implement one, and if it is worthwhile.

Would a config file be helpful, that allows you to set different parameters for each tool, as well as select which tools will run?

**Comment by gopinath6** [comment]
Config file would be good option.thanks

**Comment by SolomonSklash** [comment]
I've added a config file option in v5.0. Try it out and let me know what you think. The one included in the repo just needs the domain field set and then passed to chomp scan like this: `./chomp-scan.sh -L config`

**Comment by gopinath6** [comment]
Should add more details in readme.md or comment in config file, reg  what to set in config files for below  parameters.Whether should add file path or short/small..
SUBDOMAIN_WORDLIST
CONTENT_WORDLIST
ENABLE_HTTP=
OUTPUT_DIR=
USE_ALL=YES
NOTICA=
BLACKLIST=

**Comment by SolomonSklash** [comment]
That's on my todo list. Currently it supports only a file path, but I will add support for the built-in wordlist names. I'll also be commenting the config file more thoroughly as well.

**Comment by SolomonSklash** [comment]
Fixed. Let me know if you come across any issues. Thanks for the feedback!
