### ISSUE TITLE
Aquatone error when trying to look at the gathered screenshots

### ISSUE THREAD

**Issue by Comodooo** [SolomonSklash/chomp-scan#18]
Hi, 

Just want to start with saying that this is a awesome tool, have had some really fun weeks working with it and trying it out (and thanks for the ubuntu script ;).

Problem is when I'm using the aquatone module the screenshots become corrupted, I don't know if it's because of chromium of why this is happening.

**Comment by SolomonSklash** [comment]
Thanks for the feedback, and I'm glad you're enjoying Chomp Scan!

If you don't need to use masscan, then there is no reason to run as root. Like you've found with aquatone, any files created by Chomp Scan will be owned by root and you'll need to be root or use sudo to view them.

I'll close this for now, feel free to open a new issue if you have any more trouble.
