### ISSUE TITLE
Add CLI arguments

### ISSUE THREAD

**Issue by gopinath6** [SolomonSklash/chomp-scan#2]
Nice tool!
Any option to give all the configuration option at  starting of command itself?Currently we need to monitor tool continuously to enter option for next step..If we give all configure at first step , we can check  result after  finishing every steps

**Comment by SolomonSklash** [comment]
Thanks!

Adding command line arguments so that it doesn't need to be interactive is my top priority.

**Comment by gopinath6** [comment]
Also providing option to select particular tools(instead of executing all tools) for content discovery/information discovery would  be  good

**Comment by SolomonSklash** [comment]
I've released v3.0, with a new CLI mode. Let me know what you think. So far there is no option to select individual tools.

**Comment by gopinath6** [comment]
Thanks!
