### ISSUE TITLE
Run Subjack with HTTP and HTTPS

### ISSUE THREAD

**Issue by oldesec** [SolomonSklash/chomp-scan#21]
Currently subjack only checks "https".

```
"$SUBJACK" -d "$1" -w "$2" -v -t 20 -ssl -m -o "$WORKING_DIR"/subjack-output.txt -c "$HOME"/go/src/github.com/haccer/subjack/fingerprints.json;
```

But sometimes, there can be problems at http.

So I think , need to add a check for "http".

maybe (delete -ssl option)
```
"$SUBJACK" -d "$1" -w "$2" -v -t 20 -m -o "$WORKING_DIR"/subjack-http-output.txt -c "$HOME"/go/src/github.com/haccer/subjack/fingerprints.json;
```

**Comment by SolomonSklash** [comment]
Subjack runs really quickly, so I will have it run twice, once for HTTP and once for HTTPS. Good catch.

**Comment by SolomonSklash** [comment]
Fixed. Let me know how it works for you.
