### ISSUE TITLE
Subjack path

### ISSUE THREAD

**Issue by Krossom** [SolomonSklash/chomp-scan#22]
> [!] The path or the file specified by the path for subjack does not exit.

i did source ~/.profile

**Comment by SolomonSklash** [comment]
Can you run these commands and show me the output?
`command -v subjack`
`which subjack`
`echo $GOPATH`

**Comment by Krossom** [comment]
I think its a problem with GO cause it didnt downloaded subjack. i cant find it

**Comment by Krossom** [comment]
Hmm
```

asd@asd:~/go/bin$ ls
ffuf  gobuster  inception  subfinder  subjack  waybackurls
krossom@vukali:~/go/bin$ ./subjack
Usage of ./subjack:
  -a    Find those hidden gems by sending requests to every UR
```
??

**Comment by Krossom** [comment]
asd@asd:~/chomp-scan$ cat /etc/issue
Kali GNU/Linux Rolling \n \l

asd@asd:~/chomp-scan$ command -v subjack
asd@asd:~/chomp-scan$ which subjack
asd@asd:~/chomp-scan$ echo $GOPATH
/home/asd/go

**Comment by SolomonSklash** [comment]
Do any of the go tools work when you're not in their install directories? It looks like Subjack installed ok, but it still isn't in your $PATH.

**Comment by Krossom** [comment]
```
forgot ls ~/bounty/tools
altdns  aquatone  bfac  CORStest  dnscan  massdns  S3Scanner  Sublist3r
```

> Do any of the go tools work when you're not in their install directories? It looks like Subjack installed ok, but it still isn't in your $PATH.

nope no one of them. I think no one of them didnt install...

**Comment by SolomonSklash** [comment]
Since they are all listed in ~/go/bin, they did install. You were able to run `./subjack` and it ran, so it is installed. I really thing the issue is with the $PATH variable.
Do an `echo $PATH` and make sure that ~/go/bin is there. That's what the `source ~/.profile` is supposed to accomplish. Are you using a shell other than bash by chance?

**Comment by Krossom** [comment]
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go-workspace/bin`

... idk

**Comment by SolomonSklash** [comment]
So it is definitely missing.
This is a temporary fix, but try this.
Run `PATH=$PATH:$HOME/go/bin`
Then do `echo $PATH` and see if ~/go/bin is there and if chom-scan.sh will run.

**Comment by sabeesh03** [comment]
./subjack is a directory
