### ISSUE TITLE
Error scan

### ISSUE THREAD

**Issue by Mjunior1** [SolomonSklash/chomp-scan#28]
root@d00m:/pentest/chomp-scan# ./chomp-scan.sh -u github.com -a d short -cC large -p -o /pentest/chomp-scan/teste/
**Use all discovered domains.
[!] The path or the file specified by the path for subfinder does not exit.**
root@d00m:/pentest/chomp-scan#

**Comment by Mjunior1** [comment]
root@d00m:~/bounty/tools# ll
total 36
drwxr-xr-x 9 root root 4096 Mar 11 03:14 ./
drwxr-xr-x 3 root root 4096 Mar 11 03:13 ../
drwxr-xr-x 5 root root 4096 Mar 11 03:14 CORStest/
drwxr-xr-x 4 root root 4096 Mar 11 03:14 S3Scanner/
drwxr-xr-x 4 root root 4096 Mar 11 03:14 Sublist3r/
drwxr-xr-x 2 root root 4096 Mar 11 03:14 aquatone/
drwxr-xr-x 3 root root 4096 Mar 11 03:14 bfac/
drwxr-xr-x 3 root root 4096 Mar 11 03:14 dnscan/
drwxr-xr-x 8 root root 4096 Mar 11 03:14 massdns/
root@d00m:~/bounty/tools# pwd
/root/bounty/tools

**Comment by SolomonSklash** [comment]
Subfinder is a Go tool, so you have to make sure the ~/go/bin directory is in your $PATH variable. 
Did you run the installer and do `source ~/.profile`?
Are you running Bash or some other shell?
Can you give me the output of `echo $PATH`?

**Comment by Mjunior1** [comment]
> Subfinder is a Go tool, so you have to make sure the ~/go/bin directory is in your $PATH variable.
> Did you run the installer and do `source ~/.profile`?
> Are you running Bash or some other shell?
> Can you give me the output of `echo $PATH`?

Yes. I run 'source ~/.profile' and run ./chomp-scan.sh

```
root@d00m:/pentest/chomp-scan# ./chomp-scan.sh -u https://www.uol.com.br
[!] The path or the file specified by the path for subfinder does not exit.

```
```
root@d00m:/pentest/chomp-scan# $PATH
-bash: /usr/local/rvm/gems/ruby-2.5.3/bin:/usr/local/rvm/gems/ruby-2.5.3@global/bin:/usr/local/rvm/rubies/ruby-2.5.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/rvm/bin: No such file or directory
root@d00m:/pentest/chomp-scan#
```

**Comment by SolomonSklash** [comment]
Try taking a look at ~/.profile. It seems like it may not have added the Go path correctly.

In the meantime, you might try running `PATH=$PATH:$/root/go/bin` and then run Chomp Scan again and see if it works. If it does, then it's a problem with your PATH for sure.

**Comment by Mjunior1** [comment]
I have install Go, my PATH is:

`export PATH=/usr/local/rvm/gems/ruby-2.5.3/bin:/usr/local/rvm/gems/ruby-2.5.3@global/bin:/usr/local/rvm/rubies/ruby-2.5.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/rvm/bin:/usr/local/go/bin:`

But:

`[!] The path or the file specified by the path for subfinder does not exit.`

`root@d00m:/pentest/chomp-scan# ll /usr/local/go/bin/
total 34652
drwxr-xr-x  2 root root     4096 Feb 25 23:08 ./
drwxr-xr-x 10 root root     4096 Feb 25 23:06 ../
-rwxr-xr-x  1 root root 14568380 Feb 25 23:08 go*
-rwxr-xr-x  1 root root 17389472 Feb 25 23:08 godoc*
-rwxr-xr-x  1 root root  3513529 Feb 25 23:08 gofmt*
root@d00m:/pentest/chomp-scan# `

**Comment by SolomonSklash** [comment]
Do `ls ~/go/bin`. If you see subfinder there, then the problem is you need to add ~/go/bin.

Did you try `PATH=$PATH:$/root/go/bin`?
