### ISSUE TITLE
Create installation script

### ISSUE THREAD

**Issue by oldesec** [SolomonSklash/chomp-scan#3]
Hello.

Nice good tool.

But, Installation is difficult.

How can I work in the Ubuntu environment?

There is a difficulty in setting PATH.

Do you plan to develop an installation script?

**Comment by SolomonSklash** [comment]
I do plan on creating an installation script, as well as supporting Ubuntu and Debian.

**Comment by oldesec** [comment]
Oh.. Good news. :)

**Comment by SolomonSklash** [comment]
I've added Ubuntu 18.04 support in the latest v4.0 release, as well as an install script. Let me know how it works for you.

**Comment by oldesec** [comment]
Hello.

I checked in Ubuntu 18.04.

Good. !
