### ISSUE TITLE
Issue with inception tool

### ISSUE THREAD

**Issue by Comodooo** [SolomonSklash/chomp-scan#39]
Hey! 

After the last update I reinstalled chomp-scan and now I'm having some issues with running the inception module. 

"[!] The path or the file specified by the path for inception does not exit."

The inception program is installed under ~/go/bin as it should be I assume? I have also tried blanking it out in the config file but it still generates the same error message.

If I only try to run the tool it also come back with a error message that it's trying to locate "/src/github.com/proabiral/inception/provider.json: no such file or directory", and that is ofc because it dosn't apply the ~/ to the search path......

**Comment by SolomonSklash** [comment]
I'll look into this. Definitely sounds like a path problem.

**Comment by SolomonSklash** [comment]
Try pulling the latest release, 5.7. I added the providers.json file to the local wordlists directory and explicitly referenced it in the inception command. Please let me know if you still have any issues, but this should definitely fix it.

**Comment by Comodooo** [comment]
Still getting the issue after pulling latest release sadly.

**Comment by SolomonSklash** [comment]
Interesting. Can you try running inception against some domain by itself and see if you still get the issue? Also try adding the `-provider` flag and the path to wherever the provider.json file is located on your machine.

**Comment by SolomonSklash** [comment]
I believe I found the issue. $GOPATH was not being set. Try pulling the latest code and re-running the installer, or adding this to your ~/.profile: `export GOPATH=$HOME/go`
Then `source ~/.profile` and `echo $GOPATH` to make sure it is set.

**Comment by Comodooo** [comment]
Thanks so much for your help!

**Comment by SolomonSklash** [comment]
Glad to hear it! I appreciate your feedback and helping make Chomp Scan better.
