### ISSUE TITLE
add multi domain in config

### ISSUE THREAD

**Issue by oldesec** [SolomonSklash/chomp-scan#44]
Hi

The current tool must generate a "config" file per domain.

Ex) google.com -> config1.txt
        fb.com -> config2.txt
test.com -> config3.txt

It would be nice if could configure multiple domains in a single file.

sample file:
```
[general]
# Set domain to scan (required). Do not include a scheme, e.g. https:// or http://. Chomp Scan will add the appropriate scheme as needed.
DOMAIN= fb.com, google.com, test.com
```

**Comment by SolomonSklash** [comment]
This is a good idea. I think it's probably the simplest way for me to add support for multiple domains. Thanks for the suggestion!

**Comment by oldesec** [comment]
@SolomonSklash Thanks for the quick answer.

With your dedication, the tools are getting stronger. :)

**Comment by oldesec** [comment]
@SolomonSklash Hello.

It would be nice if had the ability to upload files to the cloud for backup.
For example, the ability to upload files using the "rclone" tool.

Ref: https://rclone.org/

**Comment by Sy3Omda** [comment]
> This is a good idea. I think it's probably the simplest way for me to add support for multiple domains. Thanks for the suggestion!

is this suggestion is ready now !
could i add more than one domain in config file separated by `,`

**Comment by SolomonSklash** [comment]
Sorry, I've not been able to get to this yet. Most likely I will have domains added to the config file separated by a comma, as it seems pretty easy to do. The main part is just checking for multiple domains and running all the tools in order, and creating the proper output directory for each. None of that is all that hard, but it does involve a lot of rearranging of code and possibly introducing bugs. I plan on getting started on it soon.

**Comment by Sy3Omda** [comment]
glad to here that, in the mean while we could create config file for each domain in the scope and concatenate the whole command in one line separated by `&&` as you know .
an idea came up to me after reading your comment that it will take some time and i SUGGEST you could invest this time in implementing a workflow page to view final result in handy way.

**Comment by SolomonSklash** [comment]
@Sy3Omda @oldesec I have implemented multiple domains in the config file. Basically just add comma separated domains to the config `DOMAIN` field.

I'd love it if you guys would test it out. There is a branch called `multi-domain`. You just have to do a `git checkout multi-domain` in the main Chomp Scan directory. If you guys find any bugs let me know, otherwise I will merge it into the main repo and cut a new release in a few days.

**Comment by oldesec** [comment]
@SolomonSklash  I finished the test.
It works well. :+1:

**Comment by SolomonSklash** [comment]
Glad to hear it, thanks for testing. I've merged it into master.
