### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#47]
I think we need to add option in config file to give user choice to shutdown computer after the script finished because in some cases this script could take 2 or more days of running.

**Comment by SolomonSklash** [comment]
I'm a little torn on this one. The script can definitely take a while, but in my experience, I've never used a feature like that in a tool, and wouldn't really trust most tools to shut down my computer. One option would be to just run Chomp Scan and then add something like `&& shutdown now`. To me that seems like a better option than adding it to the config file. Any thoughts?
