### ISSUE TITLE
Can not understand this, i think both if statement will scan same list !

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#49]
https://github.com/SolomonSklash/chomp-scan/blob/80e17512b57f289bd0bad8b7f2c4bdeeb30971a2/chomp-scan.sh#L1782

**Comment by SolomonSklash** [comment]
So $1 is the domain list, which will either be all discovered domains, or all resolved domains. The `if [[ $1 == $WORKING_DIR/$ALL_RESOLVED ]]; then` check looks for the all resolved domains list, otherwise it runs against the discovered domains. Does that make sense?

**Comment by Sy3Omda** [comment]
got it, but in any case there will be all resolved domains list so I think it will never run against all discovered domains, right!

**Comment by SolomonSklash** [comment]
It will run against all discovered domains if you pass the flag to tell it to. By default it uses all resolved, which is usually what most people would want. See the `USE_ALL` parameter in the config file.
