### ISSUE TITLE
[Info] Missing or fake domains.

### ISSUE THREAD

**Issue by oldesec** [SolomonSklash/chomp-scan#51]
Hi

I check #50.

The "all_resolved_domains.txt" file contains a lot of errors.

Missing or fake domains.

So, the performance of the tool is falling.

scan speed up.. but.. Missing domain.

In my opinion, other validation filtering seems to be required.

The massdns tool seems to generate false positives.

**Comment by SolomonSklash** [comment]
See the comments in #50. I will close this one and address false positive issues there.
