### ISSUE TITLE
What exactly this function DO?

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#53]
https://github.com/SolomonSklash/chomp-scan/blob/80e17512b57f289bd0bad8b7f2c4bdeeb30971a2/chomp-scan.sh#L778

this function couse me missed the main domain from scan more than once which is ```www.test.com``` and of course if intersting is there ``so`` all_resolved is ignored as you know.
So i am wondering what this function is really do, it`s not filtering any thing or use specific tool to say that list is really interesting.
i hope you got the idea

**Comment by SolomonSklash** [comment]
It gets any domains listed in the `interesting.txt` file. It does not get the main domain. The purpose is to quickly identify domains like admin, login, testing, etc. You can add any domains you want to the list if you are looking for something specific.
