### ISSUE TITLE
file not even exist  

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#56]
https://github.com/SolomonSklash/chomp-scan/blob/2daa4462ba458e59e309fa5a4e55e27925cb52d8/chomp-scan.sh#L1874

while i check subjack tool for the first time i found you mention a fingerprints.json with argument `-c` in go path `/go/src/github.com/haccer/subjack/` BUT this path it not exist in the first place. 
i setup the tool twice but the path it is not their !!
perhaps we need to add command to download subjack repo to mentioned PATH
could you check this out ???

**Comment by SolomonSklash** [comment]
I believe there's a typo in chomp-scan.sh. It should probably be `$GOPATH` instead of `$HOME`. Will you show me the output of `echo $GOPATH` on your system, and then try `cat $GOPATH/src/github.com/haccer/subjack/fingerprints.json` and see if it cats the fingerprints file?

**Comment by SolomonSklash** [comment]
Also make sure you have done `source ~/.profile` if you are using Bash. This will set the $GOPATH variable, which is needed for all the Go tools.

**Comment by Sy3Omda** [comment]
got it thx
