### ISSUE TITLE
problem to set custom directory

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#65]
https://github.com/SolomonSklash/chomp-scan/blob/4332d227444a464d3edc81d2b8633651a04ba490/chomp-scan.sh#L229

if suddenly the tool stopped in middle of working and i want to resume the tool after restart the pc.
as i know it could be resumed by set custom directory in current config file without creating new folder to continue scanning or brute forcing without start info gathering domain from the begging again.
the problem is when i set the full path of the working directory it keep saying `Output directory test.com-20\:01\:08 does not exist or is not writable. Please check the configuration file.`
i tried to set Custom directory in config file 
`# Set custom output directory. If multiple domains are used, this will contain each domain's output in a subdirectory.
OUTPUT_DIR=test.com-20\:01\:08`
OR `OUTPUT_DIR=\test.com-20\:01\:08\` NOT working
OR `OUTPUT_DIR=\root\chomp-scan\test.com-20\:01\:08\`
So what is the right path should be in that config file ?
BTW i made this folder as writable by using `chmod 755 test.com-20\:01\:08` to avoid writable issue and still not working

**Comment by SolomonSklash** [comment]
Are you using backslashes `\`\ or forward slashes for your paths? I'm not sure how Linux handles them as path separators. Also I'm not sure you need them to escape the colons. Otherwise you have it exactly right.
