### ISSUE TITLE
Suggestion to minimize running time by Nikto

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#70]
https://github.com/SolomonSklash/chomp-scan/blob/47a0fc91fbf381b9c33ee31aa820fe95d89f6d52/chomp-scan.sh#L1778

if you could remember our discussion about minimize time to run nikto against domains, i find out a way we could do by parsing the result of already filtered list which generated from aquatone tool.
which would be a good idea to use this list `aquatone_urls.txt` located in aquatone folder to run different tools against it and the first one would be Nikto to reduce time scanning target and avoid scanning unnecessary sub-domains .
the code would be something like 
`"$NIKTO" -h "$WORKING_DIR"/aquatone/aquatone_urls.txt -Format html -output "$WORKING_DIR"/nikto/"$ADOMAIN".html;`

**Comment by SolomonSklash** [comment]
I have merged your addition of `httprobe`, and added a check when `nikto` runs to use the `httprobe` output. This should shorten the run time by eliminating non-HTTP ports. Let me know how it works for you.
