### ISSUE TITLE
inception is not available for download

### ISSUE THREAD

**Issue by Sy3Omda** [SolomonSklash/chomp-scan#81]
https://github.com/SolomonSklash/chomp-scan/blob/c33cab7a48f0a43100e6069326b4b9e066dc9a44/install.sh#L235

the repo is deleted so we should modify this or upload old version of inception.
and modify the `chompscan.sh` not to require inception to run

**Comment by SolomonSklash** [comment]
Good catch. I've updated the code not to check for inception until we can figure out an alternative. I don't have a clone of the Github repo, but I have the bare executable.

**Comment by Sy3Omda** [comment]
another thing, why this script must run in root user rather than normal user!
I found this annoying when I must log in as root in every box (vps) or in Microsoft wsl for example

**Comment by SolomonSklash** [comment]
It doesn't have to be run as root. Only masscan requires root, in order to create raw packets. If you skip masscan,  you won't be asked to run as root. In fact, there is a warning that says you've selected masscan and not run as root. It does not show up unless you run masscan.
